### ISSUE TITLE
Problema nel file publiccode.yml

### ISSUE THREAD

**Issue by libremente** [RegioneBasilicata/SistemaInformaticoConsolidamento#1]
Buongiorno @fferrante-traccia,
purtroppo a causa di due piccoli problemi nel file publiccode.yml l'indicizzazione all'interno di Developers Italia non è ancora avvenuta correttamente.
Tali problemi sono:
```
validation ko:
description/lt/features: too long, max 100 chars
description/lt/longDescription: too short (239), min 500 chars
```
Ovvero, le feature devono avere un numero massimo di 100 caratteri ciascuna e la `longDescription` deve essere di almeno 500 caratteri.

Sistemate queste chiavi il software verrà inserito automaticamente all'interno del catalogo.
Resto a disposizione.
Grazie molte

**Comment by fferrante-traccia** [comment]
I due problemi indicati sono stati sistemati.
Saluti

**Comment by libremente** [comment]
Perfetto, grazie molte @fferrante-traccia!
